# Generated by Django 5.2.10 on 2026-05-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name_alter_category_slug'),
        ('profiles', '0002_alter_clientprofile_user_alter_freelanceprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
