# Generated by Django 5.2.10 on 2026-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_freelanceprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='company_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
