# Generated by Django 5.2.10 on 2026-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_clientprofile_company_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_logo_url',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=150),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='availability',
            field=models.CharField(blank=True, default='Available for work', max_length=100),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='experience',
            field=models.CharField(blank=True, default='2+ Years', max_length=100),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='languages',
            field=models.CharField(blank=True, default='English, Bengali', max_length=150),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='location',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=150),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Separate skills with space', max_length=300),
        ),
    ]
