# Generated by Django 5.2.10 on 2026-07-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_clientprofile_company_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='location',
        ),
    ]
