# Generated by Django 5.2.10 on 2026-07-03 09:51

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('profiles', '0006_remove_clientprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time (40+ hrs/week)'), ('part_time', 'Part Time (10–30 hrs/week)'), ('less_than_10', 'Less than 10 hrs/week'), ('as_needed', 'As Needed')], max_length=20),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancers', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher (0-1 year)'), ('junior', 'Junior (1-2 years)'), ('mid', 'Intermediate (2-5 years)'), ('senior', 'Senior (5+ years)'), ('expert', 'Expert (10+ years)')], max_length=20),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Example: English, Bangla', max_length=200),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Separate skills with commas', max_length=300),
        ),
    ]
