# Generated by Django 5.2.10 on 2026-07-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_clientprofile_city_clientprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='city',
        ),
    ]
