# Generated by Django 5.2.10 on 2026-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_clientprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/covers/'),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='freelancers/covers/'),
        ),
    ]
