# Generated by Django 5.2.10 on 2026-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name_alter_category_slug'),
        ('profiles', '0010_clientprofile_country_freelanceprofile_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='categories.category'),
        ),
    ]
