# Generated by Django 5.2.10 on 2026-05-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
