# Generated by Django 5.2.10 on 2026-05-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('message', 'Message')], default='proposal', max_length=20),
        ),
    ]
