# Generated by Django 5.2.10 on 2026-05-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_redirect_url'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='proposals.proposal'),
        ),
    ]
