# Generated by Django 5.2.10 on 2026-05-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='proposal',
        ),
    ]
